<h4>Liste des couleurs - <a href="javascript:void(0);" onclick="addcouleur()">Ajouter une couleur</a></h4>

<?php foreach ($couleurs as $couleur) : ?>
	<p><?php echo $this->escapeHtml($couleur->nom); ?> 

	<a href="javascript:void(0);" onclick="editcouleur(<?php echo $couleur->id; ?>)">Editer</a>
	<a href="javascript:void(0);" onclick="deletecouleur(<?php echo $couleur->id; ?>)">Supprimer</a>

</p>
<?php endforeach; ?>
